config/routes.rb
Edurange::Application.routes.draw do

  #Static tutorial routes
  get 'tutorials/index'
  get 'tutorials/making_scenarios'
  get 'tutorials/student_manual'
  get 'tutorials/instructor_manual'
  get 'tutorials/quick_start_guide'

  get 'tutorials/ssh_inception'
  get 'tutorials/total_recon'

  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds
  resources :tutorials
  resources :statistics do
    member do  # define routing for the statistics controller methods
      # destorying statistics
      post 'destroyme'
      # downloading statistics
      get 'download_bash_history'
      get 'download_exit_status'
      get 'download_script_log'
      get 'download_all'  
      # analytics, complicated query params
      get 'generate_analytics' 
    end
  end
  

  get 'statistic/id', to: 'scenarios#id'
  

  resources :scenarios do
    member do
      post 'destroyme'

      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'
      post 'status'
      post 'pause'
      post 'start'

      post 'log_get'
      post 'clone'
      post 'clone_new'
      get  'clone_set'
      post 'save'
      post 'save_as'
      post 'obliterate_custom'

      post 'instructions_get'
      post 'instructions_modify'
      post 'instructions_student_get'
      post 'instructions_student_modify'

      post 'cloud_add'
      post 'cloud_delete'
      post 'cloud_modify'

      post 'subnet_add'
      post 'subnet_delete'
      post 'subnet_modify'

      post 'instance_add'
      post 'instance_bash_history'
      post 'instance_chef_error'
      post 'instance_delete'
      post 'instance_modify'
      post 'instance_role_add'
      post 'instance_role_remove'
      post 'instance_dynamic_ip_roll'

      post 'group_add'
      post 'group_modify'
      post 'group_delete'

      post 'group_instructions_get'
      post 'group_instructions_modify'

      post 'group_player_add'
      post 'group_player_delete'
      post 'group_student_group_add'
      post 'group_student_group_remove'

      post 'group_admin_access_add'
      post 'group_admin_access_remove'
      post 'group_user_access_add'
      post 'group_user_access_remove'

      post 'role_add'
      post 'role_delete'
      post 'role_modify'
      post 'role_package_add'
      post 'role_package_remove'
      post 'role_recipe_add'
      post 'role_recipe_remove'

      post 'recipe_view'
      post 'recipe_update_view'
      post 'recipe_global_get'
      post 'recipe_global_add'
      post 'recipe_custom_add'
      post 'recipe_remove'
      post 'recipe_update'

      post 'scoring_question_add'
      post 'scoring_question_delete'
      post 'scoring_question_modify'
      post 'scoring_question_move_up'
      post 'scoring_question_move_down'

      post 'scoring_answers_show'
      post 'scoring_answer_essay_show'
      post 'scoring_answer_essay_grade'
      post 'scoring_answer_essay_grade_edit'
      post 'scoring_answer_essay_grade_delete'
      post 'scoring_answer_comment'
      post 'scoring_answer_comment_show'
      post 'scoring_answer_comment_edit'
      post 'scoring_answer_comment_edit_show'

    end
  end

  post 'scenarios/create_custom'
  post 'scenarios/obliterate_custom'
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get  'admin', to: 'admin#index'
  post 'admin/user_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'
  post 'admin/student_add_to_all'
  post 'admin/instructor_to_student'
  post 'admin/reset_password'
  post 'admin/student_group_create'
  post 'admin/student_group_destroy'
  post 'admin/student_group_user_add'
  post 'admin/student_group_user_remove'

  get 'instructor', to: 'instructor#index'
  post 'instructor/student_group_create'
  post 'instructor/student_group_destroy'
  post 'instructor/student_group_user_add'
  post 'instructor/student_group_user_remove'

  get 'student', to: 'student#index'
  get 'student/:id', to: 'student#show'
  post 'student/:id/answer_string', to: 'student#answer_string', as: 'answer_string_student'
  post 'student/:id/answer_number', to: 'student#answer_number', as: 'answer_number_student'
  post 'student/:id/answer_essay', to: 'student#answer_essay', as: 'answer_essay_student'
  post 'student/:id/answer_essay_delete', to: 'student#answer_essay_delete', as: 'answer_essay_delete_student'
  post 'student/:id/answer_essay_show', to: 'student#answer_essay_show', as: 'answer_essay_show_student'
  post 'student/:id/answer_comment_show', to: 'student#answer_comment_show', as: 'answer_comment_show_student'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/views/admin/_instructor.html.haml
%tr{ id: "user-#{user.id}"}
  %td= user.name
  %td= user.email
  %td= user.organization
  %td.text-right
    = link_to 'delete', admin_user_delete_path(id: user.id), remote: true, method: :post, :data => { :confirm => "Are you sure you want to delete Instructor #{user.name}?" }
    |
    = link_to 'make student', admin_instructor_to_student_path(id: user.id), remote: true, method: :post, :data => { :confirm => "Are you sure you want to make Instructor #{user.name} a student? This will erase all students accounts belonging to instructor." }
    |
    = link_to 'reset password', admin_reset_password_path(id: user.id), remote: true, method: :post, :data => { :confirm => "This will assign the user a random password and email it to them. Are you sure?" }

app/views/admin/_student.html.haml
%tr{ id: "user-#{user.id}" }
  %td= check_box_tag "id[]", user.id
  %td= user.name
  %td= user.email
  %td= user.organization
  %td.text-right
    = link_to 'delete', admin_user_delete_path(id: user.id), remote: true, method: :post, :data => { :confirm => "Are you sure you want to delete Student #{user.name}?" }
    |
    = link_to 'make instructor', admin_student_to_instructor_path(id: user.id), remote: true, method: :post, :data => { :confirm => "Are you sure you want to make Student #{user.name} an instructor?" }
    |
    = link_to 'reset password', admin_reset_password_path(id: user.id), remote: true, method: :post, :data => { :confirm => "This will assign the user a random password and email it to them. Are you sure?" }
    |
    = link_to 'add to All', admin_student_add_to_all_path(id: user.id), remote: true, method: :post

app/views/admin/_student_group.html.haml
%div{ id: "student-group-#{student_group.id}" }

  - if student_group.name != "All"
    %span.pull-right
      = link_to '- delete group', admin_student_group_destroy_path(student_group_id: student_group.id),
          remote: true, method: :post, role: "button",
          data: { confirm: "Are you sure you want to delete Student Group #{student_group.name}?" }
  %label
    = student_group.name + ":"
    = link_to 'expand/collapse', "#student-group-#{student_group.id}",
      data: { toggle: 'collapse', target: "#student-group-#{student_group.id}-collapse", parent: '#student_groups' }

  %div.collapse{ id: "student-group-#{student_group.id}-collapse", class: (student_group.name == "All" ? "in" : "") }

    = form_tag '#', remote: true, method: :post, class: 'form-inline' do

      %table.table{ id: "student-group-#{student_group.id}-table"}
        %tr
          %td
            <a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked',true);">all</a>,
            <a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked',false);">none</a>
          %th Name
          %th Email
          %th Organization
          %th
        - student_group.student_group_users.each do |student|
          = render 'student_group_student', student: student, student_group: student_group
        %tr#foot
          %td{ colspan: '5' }
            <a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked',true);">all</a>,
            <a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked',false);">none</a>,
            %b with selected:
            - if student_group.name == "All"
              = link_to 'add to ', "javascript:void(0)",
                onclick: "$('#student-group-#{student_group.id} form').attr('action','#{admin_student_group_user_add_path}');$('#student-group-#{student_group.id} form').submit();"
              = (select_tag 'student_group_name',
                options_for_select(StudentGroup.all.select{ |s| s.name != "All" and s.user.id == current_user.id }.collect{ |s| s.name }),
                class: 'form-control input-sm', id: 'student-group-select') + ','
            = link_to 'remove', "javascript:void(0)",
              onclick: "$('#student-group-#{student_group.id} form').attr('action','#{admin_student_group_user_remove_path}');$('#student-group-#{student_group.id} form').submit();"

app/views/admin/_student_group_student.html.haml
%tr{ id: "user-#{student.user.id}", class: "student-group-user-#{student.id}" }
  %td= check_box_tag "student_group_user_id[]", student.id
  %td= student.user.name
  %td= student.user.email
  %td= student.user.organization
  %td.text-right
    = link_to 'add to student group', '#modal-student-group-user-add', data: {toggle: "modal"}, |
      onclick:  "$('#modal-student-group-user-add').find('#user-name').html('#{student.user.name}');" + |
                "$('#modal-student-group-user-add').find('#student_group_user_id').val('#{student.id}');" + |
                "$('#modal-student-group-user-add').find('#name-div').removeClass('has-error');" + |
                "$('#modal-student-group-user-add').find('#student_group_name').val('');" + |
                "$('#modal-student-group-user-add').find('#name-help').html('');" |
    |
    = link_to 'remove', admin_student_group_user_remove_path(student_group_user_id: student.id), remote: :true, method: :post, data: { confirm: "Are you sure you want to delete Student Group User #{student.user.name}?" }

app/views/admin/index.html.haml
= render 'admin/modals/create_instructor'
= render 'admin/modals/student_group_create'
= render 'admin/modals/student_group_user_add'

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h3
        Admin Home

  %div.panel-body
    = render 'partials/account_information.html.haml'
    %hr

    %label AWS Settings:
    - if not @aws_working
      %div.failure
        FAILED TO VALIDATE CREDENTIALS
    %div.row
      %div.col-sm-6
        %b Access Key ID:
        = ENV["AWS_ACCESS_KEY_ID"].sub(/^.............../, "...............")
        %br
        %b Access Key:
        = ENV["AWS_SECRET_ACCESS_KEY"].sub(/^.................................../,
            "...................................")
        %br
        %b Region:
        = ENV["AWS_REGION"]
        %br
        %b EC2 Key:
        = Settings.ec2_key
      %div.col-sm-6
        %b Bucket Name:
        = Settings.bucket_name
        %br
        %b VPC Limit:
        = Settings.vpc_limit
        %br
        %b AMI NAT:
        = Settings.ami_nat
        %br
        %b AMI Ubuntu:
        = Settings.ami_ubuntu

    %hr

    %label Registration Code:
    %dl
      = @user.registration_code
    %p

    %hr

    %label User Information:

    %dl
      %span.pull-right= link_to '+ create instructor', "#modal-create-instructor", :data => {:toggle=>"modal"}, |
              onclick: "$('#modal-create-instructor').find('#email').val('');" +                  |
                       "$('#modal-create-instructor').find('#name').val('');" +                   |
                       "$('#modal-create-instructor').find('#organization').val('');"             |
      %label Instructors:
      %dl

        %table.table#instructors-table
          %tr
            %th Name
            %th Email
            %th Organization
            %th
          - @instructors.each do |user|
            = render 'instructor', user: user

      %label
        Students:
        = link_to 'expand/collapse', '#students-table',
            data: { toggle: 'collapse', target: '#students-table-collapse' }

      %dl
        %div.collapse.in#students-table-collapse
          = form_tag '#', method: :post, remote: true, class: 'form-inline', id: 'students-table-form' do
            = hidden_field_tag 'action', value: 'delete'
            %table.table#students-table
              %tr
                %td
                  <a href="javascript:$('#students-table input:checkbox').prop('checked', true);">all</a>,
                  <a href="javascript:$('#students-table input:checkbox').prop('checked', false);">none</a>
                %th Name
                %th Email
                %th Organization
                %th
              - @students.each do |user|
                = render 'student', user: user
              %tr#foot
                %td{ colspan: "5" }
                  <a href="javascript:$('#students-table input:checkbox').prop('checked', true);">all</a>,
                  <a href="javascript:$('#students-table input:checkbox').prop('checked', false);">none</a>,
                  %b with selected:
                  = (link_to 'add to all', "javascript:void(0);",
                    onclick: "$('#students-table-form').attr('action', '#{admin_student_add_to_all_path}');$('#students-table-form').submit();") + ','
                  = link_to('delete', "javascript:void(0);", remote: true, method: :post,
                    onclick: "$('#students-table-form').attr('action', '#{admin_user_delete_path}');$('#students-table-form').submit();",
                    :data => { :confirm => "Are you sure you want to delete all selected students?" })

      %span.pull-right= link_to '+ create student group', '#modal-student-group-create', data: {toggle: "modal"}, onclick: "$('#modal-student-group-create').find('#name-div').removeClass('has-error'); $('#modal-student-group-create').find('#name').val(''); $('#modal-student-group-create').find('#name-help').html(''); "
      %label Student groups:
      %dl
        %dl{ id: "student-groups" }
          - @user.student_groups.each do |student_group|
            = render 'student_group', student_group: student_group, scenario: @scenario