config/routes.rb
Edurange::Application.routes.draw do

  #Static tutorial routes
  get 'tutorials/index'
  get 'tutorials/making_scenarios'
  get 'tutorials/student_manual'
  get 'tutorials/instructor_manual'
  get 'tutorials/quick_start_guide'

  get 'tutorials/ssh_inception'
  get 'tutorials/total_recon'

  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds
  resources :tutorials
  resources :statistics do
    member do  # define routing for the statistics controller methods
      # destorying statistics
      post 'destroyme'
      # downloading statistics
      get 'download_bash_history'
      get 'download_exit_status'
      get 'download_script_log'
      get 'download_all'  
      # analytics, complicated query params
      get 'generate_analytics' 
    end
  end
  

  get 'statistic/id', to: 'scenarios#id'
  

  resources :scenarios do
    member do
      post 'destroyme'

      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'
      post 'status'
      post 'pause'
      post 'start'

      post 'log_get'
      post 'clone'
      post 'clone_new'
      get  'clone_set'
      post 'save'
      post 'save_as'
      post 'obliterate_custom'

      post 'instructions_get'
      post 'instructions_modify'
      post 'instructions_student_get'
      post 'instructions_student_modify'

      post 'cloud_add'
      post 'cloud_delete'
      post 'cloud_modify'

      post 'subnet_add'
      post 'subnet_delete'
      post 'subnet_modify'

      post 'instance_add'
      post 'instance_bash_history'
      post 'instance_chef_error'
      post 'instance_delete'
      post 'instance_modify'
      post 'instance_role_add'
      post 'instance_role_remove'
      post 'instance_dynamic_ip_roll'

      post 'group_add'
      post 'group_modify'
      post 'group_delete'

      post 'group_instructions_get'
      post 'group_instructions_modify'

      post 'group_player_add'
      post 'group_player_delete'
      post 'group_student_group_add'
      post 'group_student_group_remove'

      post 'group_admin_access_add'
      post 'group_admin_access_remove'
      post 'group_user_access_add'
      post 'group_user_access_remove'

      post 'role_add'
      post 'role_delete'
      post 'role_modify'
      post 'role_package_add'
      post 'role_package_remove'
      post 'role_recipe_add'
      post 'role_recipe_remove'

      post 'recipe_view'
      post 'recipe_update_view'
      post 'recipe_global_get'
      post 'recipe_global_add'
      post 'recipe_custom_add'
      post 'recipe_remove'
      post 'recipe_update'

      post 'scoring_question_add'
      post 'scoring_question_delete'
      post 'scoring_question_modify'
      post 'scoring_question_move_up'
      post 'scoring_question_move_down'

      post 'scoring_answers_show'
      post 'scoring_answer_essay_show'
      post 'scoring_answer_essay_grade'
      post 'scoring_answer_essay_grade_edit'
      post 'scoring_answer_essay_grade_delete'
      post 'scoring_answer_comment'
      post 'scoring_answer_comment_show'
      post 'scoring_answer_comment_edit'
      post 'scoring_answer_comment_edit_show'

    end
  end

  post 'scenarios/create_custom'
  post 'scenarios/obliterate_custom'
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get  'admin', to: 'admin#index'
  post 'admin/user_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'
  post 'admin/student_add_to_all'
  post 'admin/instructor_to_student'
  post 'admin/reset_password'
  post 'admin/student_group_create'
  post 'admin/student_group_destroy'
  post 'admin/student_group_user_add'
  post 'admin/student_group_user_remove'

  get 'instructor', to: 'instructor#index'
  post 'instructor/student_group_create'
  post 'instructor/student_group_destroy'
  post 'instructor/student_group_user_add'
  post 'instructor/student_group_user_remove'

  get 'student', to: 'student#index'
  get 'student/:id', to: 'student#show'
  post 'student/:id/answer_string', to: 'student#answer_string', as: 'answer_string_student'
  post 'student/:id/answer_number', to: 'student#answer_number', as: 'answer_number_student'
  post 'student/:id/answer_essay', to: 'student#answer_essay', as: 'answer_essay_student'
  post 'student/:id/answer_essay_delete', to: 'student#answer_essay_delete', as: 'answer_essay_delete_student'
  post 'student/:id/answer_essay_show', to: 'student#answer_essay_show', as: 'answer_essay_show_student'
  post 'student/:id/answer_comment_show', to: 'student#answer_comment_show', as: 'answer_comment_show_student'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_user

  def index
      #@tutorials = Tutorial.all
  end

  def making_scenarios
  end

  def instructor_manual
    send_file("#{Rails.root}/app/views/tutorials/EDURange_for_faculty.pdf", :disposition => 'inline',:type => 'application/pdf')
  end

  def student_manual
    send_file("#{Rails.root}/app/views/tutorials/EDURange_for_students.pdf", :disposition => 'inline',:type => 'application/pdf')
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(current_user.id)
    end

end

app/helpers/tutorial_helper.rb
module TutorialHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/index.html.haml
%nav.navbar.navbar-default
  %a.navbar-brand
    Help Documentation 

  %ul.nav.nav-tabs

    %li{role: 'presentation', class: params[:controller] == 'tutorials' ? "active" : "" }
      = link_to 'Help Docs', tutorials_path

    // Only display relevant docs for admin or instructor
    - if @user.is_admin? or @user.is_instructor?

      %li{role: 'presentation' }
        = link_to 'Quick Start', tutorials_quick_start_guide_path

      %li{role: 'presentation' }
        = link_to 'Making Scenarios', tutorials_making_scenarios_path

      %li{role: 'presentation'}
        = link_to 'Instructor Manual', tutorials_instructor_manual_path

    // Only display student docs
    - if @user.is_student?

      %li{role: 'presentation'}
        = link_to 'SSH Inception Help', tutorials_ssh_inception_path
     
      %li{role: 'presentation'}
        = link_to 'Total Recon Help', tutorials_total_recon_path

    %li{role: 'presentation'}
      = link_to 'Student Manual', tutorials_student_manual_path

%article{:role => "article", :class => "span9"}

  %h2 
    EDURange - Help Docs
  %font{:size => 4}
    Welcome to the EDURange Help Documentation. These pages provide a number
    of tutorials and reference guides for instructors as well as students.
    If you have a question that is not covered in these docs, please feel
    to reach out to
    %a
      = mail_to('admin@edurange.org', 'EDURange help.')
    If there are topics you would like to see covered here, please let us
    know.

    - if @user.is_admin? or @user.is_instructor?
      %br
      %br
      %h3
        EDURange project information:
      %li
        %a
          = link_to 'EDURange Project Blog', 'http://blogs.evergreen.edu/edurange/'
        <br/> This page provides information about our NSF backing, our mission,
        and our project goals.
        <br/>
        <br/>        
      %li
        %a
          = link_to 'EDURange Github', 'https://github.com/edurange/edurange-server'
        <br/> Our Github Repository. Feel free to look around or make a pull request.
        <br/>
        <br/>

    - if @user.is_student?
      %br
      %br
      %h3
        New to EDURange? 
      If you're doing a scenario other than 
      SSH Inception but are unfamiliar with ssh, you might find the
      %a
        = link_to('SSH Inception help section', 'tutorials_ssh_inception_path')
      a useful place to start.
      %br
      %br
      %h3
        Online Security Resources:
      %li
        %a
          = link_to 'Bandit Wargame', 'http://overthewire.org/wargames/bandit/'
        <br/> Bandit is one of the best places to start for those interested in learning
        about bash and wargames. "The Bandit wargame is aimed at absolute beginners. 
        It will teach the basics needed to be able to play other wargames."
        <br/>
        <br/>
      %li
        %a
          = link_to 'Pico CTF', 'https://picoctf.com/'
        <br/> PicoCTF is a 'capture the flag' computer security game on easy mode. 
        <br/>
        <br/>
      %li
        %a
          = link_to 'Smash the Stack', 'http://smashthestack.org/'
        <br/> This site hosts a number of wargames. "A wargame, in this context, is an 
        environment that simulates software vulnerabilities and allows for the legal 
        execution of exploitation techniques."
        <br/>
        <br/>
 
  %br
  %br
  %br

app/views/tutorials/instructor_manual.html.haml
%nav.navbar.navbar-default
  %a.navbar-brand
    Tutorials 

  %ul.nav.nav-tabs

    %li{role: 'presentation', class: params[:controller] == 'tutorials' ? "active" : "" }
      = link_to 'Quick Start', tutorials_path

    /
      %li{role: 'presentation', class: params[:controller] == 'scenarios' ? "active" : "" }
        = link_to 'Making Scenarios', tutorials_making_scenarios_path

    %li{role: 'presentation'}
      = link_to 'Instructor Manual', tutorials_instructor_manual_path

    %li{role: 'presentation'}
      = link_to 'Student Manual', tutorials_student_manual_path

app/views/tutorials/making_scenarios.html.haml
%nav.navbar.navbar-default
  %a.navbar-brand
    Help Documentation

  %ul.nav.nav-tabs

    %li{role: 'presentation'}
      = link_to 'Help Docs', tutorials_path

    %li{role: 'presentation'}
      = link_to 'Quick Start', tutorials_quick_start_guide_path

    %li{role: 'presentation', class: params[:controller] == 'tutorials' ? "active" : "" }
      = link_to 'Making Scenarios', tutorials_making_scenarios_path

    %li{role: 'presentation'}
      = link_to 'Instructor Manual', tutorials_instructor_manual_path

    %li{role: 'presentation'}
      = link_to 'Student Manual', tutorials_student_manual_path

%article{:role => "article", :class => "span9"}

  %h2 
    EDURange - Making Scenarios
  %font{:size => 4}
    This is a guide for creating and modifying scenarios. The details are likely to change as we
    continue to work on the user interface, but the generalities should remain the same. We're
    always excited to see people develop their own scenarios and modifications, so we'd love to
    help if you run into any trouble. You can contact us at 
    %a
      = mail_to('admin@edurange.org', 'EDURange help.')
  

  %h3 
    I. Clone an existing scenario

  %font{:size => 4}
    From the scenarios tab, load a new scenario. Select the clone button next to the scenario you wish
    to clone. 

  %h3 
    II. Add or modify new instances and subnets

  %font{:size => 4}
    Instances are just standard linux VMs that you can configure with scripts called recipes.
    If you don't plan to add any new instances to the scenario, you can skip this step. The order isn't
    important either. If you want to add roles and recipes before adding instances, you can do that.
    New instances are created with the dropdown menu besides 'Instances', right below Player_Subnet.
    You will have to fill in four fields: Name, IP Address, Internet Accessible, and Operating System.
    Name should be an alphanumeric string containing no spaces. IP can be anything in the range of the
    subnet it is under. Instances can't be internet accessible unless the subnet they are under is
    internet accessible. Most instances will have Ubuntu as their OS, but there should be more options
    in the future. You may also create or modify subnets in a similar fashion. The fields required for
    the creation of a new subnet are Name, CIDR, and Internet Accessible. You will need to specify a
    CIDR that doesn't overlap with that of another subnet.

  %h3 
    III. Make new recipe

  %font{:size => 4}
    Recipes are the way instances are modified. They are usually bash scripts and a bit of ruby packaging.
    The Recipes drop down button is below the Roles section. You can add Global Recipes, which are recipes
    we have made for various scenarios, or you can make your own Custom Recipes. To make your own,
    I suggest copying an existing recipe, and then delete your code between the "code <<-EOH" line
    and the second "EOH" line. Add your bash script between the EOH lines.

  %h3 
    IV. Make a new role (or use existing), add recipes and packages to role

  %font{:size => 4}
    Roles are the way to add packages (such as nmap, emacs, htop) and recipes to instances. Use the Role 
    drop-down button to create a new one. Then under the new role, you can add the packages and recipes you want.

  %h3 
    V. Add role to instance

  %font{:size => 4}
    Once you've created your roles and added the packages and recipes you want, scroll up to the Instances section.
    Select the drop-down button by the instance you want, and add the role you want to give that instance. You can
    use the same role on multiple instances. Instances can also have multiple roles, which simply means that all the
    recipes and packages from all roles will be added to that instance. An instance must be unbooted in order to 
    recieve a new role.

    %h3 
      VI. Modify questions / answers

    %font{:size => 4}
      The Questions section is at the bottom of the page. You can use the drop down button by Questions to create
      new questions. As you are creating a question, you can add values and the points students receive when they
      answer the questions with those values. There are various options for questions -- they can be number,
      strings, or essay answers, and each of these has additional options.

  %h3 
    VII. Add and configure student teams

  %font{:size => 4}      
    Below the instances section, you will find Teams. Using the drop down menu, you can add new teams. The main
    function of teams is that they allow you to control which students have access to which instances. Furthermore,
    you can specify who has normal access and who has full sudo access. Select the drop-down button by Admin Access
    or User Access for the given team you want to modify. Then select the instances you would like that the members
    of that team to access. After you have added all the instances for that team, select the drop down by the team's
    name. Select "Add Student Group" to add a group of students to this scenario.
    </br>
    </br>
    </br>
  %font{:size => 3}      
    Created by Jeff Ladish

app/views/tutorials/quick_start_guide.html.haml
%nav.navbar.navbar-default
  %a.navbar-brand
    Help Documentation

  %ul.nav.nav-tabs

    %li{role: 'presentation'}
      = link_to 'Help Docs', tutorials_path

    %li{role: 'presentation', class: params[:controller] == 'tutorials' ? "active" : "" }
      = link_to 'Quick Start', tutorials_quick_start_guide_path

    %li{role: 'presentation'}
      = link_to 'Making Scenarios', tutorials_making_scenarios_path

    %li{role: 'presentation'}
      = link_to 'Instructor Manual', tutorials_instructor_manual_path

    %li{role: 'presentation'}
      = link_to 'Student Manual', tutorials_student_manual_path

%article{:role => "article", :class => "span9"}

  %h2 
    EDURange - Quick Setup
  %font{:size => 4}
    This page will offer a brief tutorial for a new instructor to get scenarios up and running. 
    If you're looking for more advanced documentation on how to take advantage of all the features
    of edurange, you should consult the  
    %a
      = link_to 'Instructor Manual.', tutorials_instructor_manual_path
    If you run into trouble with any of the
    content covered in this guide, feel free to reach out to
    %a
      = mail_to('admin@edurange.org', 'EDURange help.')

    If you are new to edurange, please follow all the steps carefully. The order of steps is important!
    %a
      = mail_to('admin@edurange.org', 'EDURange help')
    and they will email you with
    account credentials. Log in to cloud.edurange.org.

  %h3
    II. Give students registration code and have students sign up on cloud.edurange.org

  %font{:size => 4}
    In order for students to sign up at cloud.edurange.org, they need a registration code.
    You can find your code on the home tab under the heading,
    "Registration Code:" (It is located below AWS Settings and above User Information, it
    should be an alphanumeric string like '23a6e9k2a5').

    Give this code to your students and have them sign up at cloud.edurange.org. Students will
    need to provide the registration code and a name, email, and password.

  %h3 
    III. Create a student group
  
  %font{:size => 4}
    On your
    %a{ :href => 'https://cloud.edurange.org/instructor'}
      home page,
    scroll down to find
    the blue button called "Create Student Groups". Once your group is created, you should see
    the new empty group under Student Groups, above the default group 'All'.

  %h3 
    IV. Add all students to student group

  %font{:size => 4}
    Once students have registered with the Registration Code you provided them, they should appear
    under the 'All' group. To add them to the new student group you have created, click on the blue
    'add to student group' link located to the right of the student's name and email. Enter the name of 
    your newly created student group to add them to that group.

  %h3 
    V. Create Scenario

  %font{:size => 4}
    Select the 'Scenario' tab at the top of the page. Select the white button 'Load New Scenario'.
    Most scenarios will be listed under 'Production Scenarios'. If you have designed and built
    your own scenarios, those will be listed under 'Custom Scenarios'.

  %h3 
    VI. Add student group to scenario

  %font{:size => 4}
    Now that the scenario is created, scroll down to the section labeled 'Groups'. You should multiple groups. 
    , including Instructor and one or more groups for students. Click the drop down menu next to a group you would
    like add students to, and and select 'Add Student Group'. Input the name of the student group that contains your students. 
    It is important that you add your student <strong>group</strong> before you boot your scenario. If you have already
    booted the scenario, unboot it, add the student group, and the boot it again.

%h3 
  VII. Boot scenario

%font{:size => 4}
  At the top of the scenario page, click the 'Boot' button on the left. The full booting process
  can take anywhere from five minutes on smaller scenarios, to fifteen minutes on the larger 
  scenarios (like recon). Once the scenario is booted and fully initialized, your students should
  be able to use their credentials (which they can see once logged into cloud.edurange.edu), to
  ssh to the NAT instance.

%br
%br
%footer
 
  %br
  %br
  %br

app/views/tutorials/ssh_inception.html.haml
%nav.navbar.navbar-default
  %a.navbar-brand
    Help Documentation 

  %ul.nav.nav-tabs

    %li{role: 'presentation' }
      = link_to 'Help Docs', tutorials_path

    %li{role: 'presentation', class: params[:controller] == 'tutorials' ? "active" : "" }
      = link_to 'SSH Inception Help', tutorials_ssh_inception_path
     
    %li{role: 'presentation'}
      = link_to 'Total Recon Help', tutorials_total_recon_path

    %li{role: 'presentation'}
      = link_to 'Student Manual', tutorials_student_manual_path


%article{:role => "article", :class => "span9"}

  %h2 
    SSH Inception Help

  %font{:size => 4}
    Welcome to the Help page for the scenario SSH Inception. The purpose of this scenario
    is to familiarize you with the basics of ssh. We have also included some advanced
    challenges for students at more advanced levels.
    <br/>
    <br/>

  %font{:size => 4}
    %li
      %a
        = link_to 'Putty Download', 'http://www.putty.org/'
      <br/> Putty is an SSH and telnet client, because unlike every mature opperating system
      on the planet, Windows still doesn't ship with one.
      <br/>
      <br/>
    %li
      %a
        = link_to 'Dartmouth Putty Tutorial', 'http://www.cs.dartmouth.edu/~campbell/cs50/putty-cygwin-tutorial.pdf'
      <br/> A tutorial for Windows users new to Putty.
      <br/>
      <br/>
    %li
      %a
        = link_to 'SSH Tutorial', 'http://support.suso.com/supki/SSH_Tutorial_for_Linux'
      <br/> This is an introduction and tutorial to ssh on linux, but it mostly applies to ssh on
      OSX as well. In the ssh_inception scenario, you will practice using ssh to connect from
      one server to the next, and then the next...
      <br/>
      <br/>

    %li
      %a
        = link_to 'Linux Command Tutorial', 'http://linuxcommand.org/lc3_lts0020.php'
      <br/> This site is a great resource for learning the basics of bash. This knowledge is
      essential for managing machines remotely.
      <br/>
      <br/>
    %li
      %a
        = link_to 'FTP Tutorial', 'http://www.webmonkey.com/2010/02/ftp_for_beginners/'
      <br/> FTP is much worse than SCP. If you have the choice, only use SCP. In reality,
      many people still use FTP, for goodness knows what reason.
      <br/>
      <br/>
    
        

app/views/tutorials/student_manual.html.haml
%nav.navbar.navbar-default
  %a.navbar-brand
    Tutorials 

  %ul.nav.nav-tabs

    %li{role: 'presentation', class: params[:controller] == 'tutorials' ? "active" : "" }
      = link_to 'Quick Start', tutorials_path

    /
      %li{role: 'presentation', class: params[:controller] == 'scenarios' ? "active" : "" }
        = link_to 'Making Scenarios', tutorials_making_scenarios_path

    %li{role: 'presentation'}
      = link_to 'Instructor Manual', tutorials_instructor_manual_path

    %li{role: 'presentation'}
      = link_to 'Student Manual', tutorials_student_manual_path

app/views/tutorials/total_recon.html.haml
%nav.navbar.navbar-default
  %a.navbar-brand
    Help Documentation 

  %ul.nav.nav-tabs

    %li{role: 'presentation' }
      = link_to 'Help Docs', tutorials_path

    %li{role: 'presentation' }
      = link_to 'SSH Inception Help', tutorials_ssh_inception_path
     
    %li{role: 'presentation', class: params[:controller] == 'tutorials' ? "active" : "" }
      = link_to 'Total Recon Help', tutorials_total_recon_path

    %li{role: 'presentation'}
      = link_to 'Student Manual', tutorials_student_manual_path


%article{:role => "article", :class => "span9"}

  %h2 
    Total Recon Help

  %font{:size => 4}
    Welcome to the Help page for the scenario Total Recon. The purpose of this scenario
    is to teach the basics of nmap, the network mapper.
  %br
  %br
  %font{:size => 4}
    %li
      %a
        = link_to 'nmap man page', 'http://linuxcommand.org/man_pages/nmap1.html'
      <br/> This is a copy of the nmap man page. You can also look at this with [man nmap],
      but it can be useful to have a copy you can view from your browser as well.
      <br/>
      <br/>
    %li
      %a
        = link_to 'nmap tutorial', 'https://nmap.org/bennieston-tutorial/'
      <br/> The nmap.org site provides a lot of documentation. This tutorial is a good place
      to get started. Of course, all of this information can be found in the nmap man page
      [man nmap], but it can be somewhat difficult to find the right option. Remember that nmap
      is not just a command -- it's a network reconnaissance tool with broad functionality.
      <br/>
      <br/>

    %li
      %a
        = link_to 'netcat help', 'http://www.cyberciti.biz/faq/linux-port-scanning/'
      <br/> There are times when nmap is not available. When you find yourself with no where
      else to turn, there is netcat. Be not afraid.
      <br/>
      <br/>