config/routes.rb
Edurange::Application.routes.draw do

  #Static tutorial routes
  get 'tutorials/index'
  get 'tutorials/making_scenarios'
  get 'tutorials/student_manual'
  get 'tutorials/instructor_manual'
  get 'tutorials/quick_start_guide'

  get 'tutorials/ssh_inception'
  get 'tutorials/total_recon'

  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds
  resources :tutorials
  resources :statistics do
    member do  # define routing for the statistics controller methods
      # destorying statistics
      post 'destroyme'
      # downloading statistics
      get 'download_bash_history'
      get 'download_exit_status'
      get 'download_script_log'
      get 'download_all'  
      # analytics, complicated query params
      get 'generate_analytics' 
    end
  end
  

  get 'statistic/id', to: 'scenarios#id'
  

  resources :scenarios do
    member do
      post 'destroyme'

      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'
      post 'status'
      post 'pause'
      post 'start'

      post 'log_get'
      post 'clone'
      post 'clone_new'
      get  'clone_set'
      post 'save'
      post 'save_as'
      post 'obliterate_custom'

      post 'instructions_get'
      post 'instructions_modify'
      post 'instructions_student_get'
      post 'instructions_student_modify'

      post 'cloud_add'
      post 'cloud_delete'
      post 'cloud_modify'

      post 'subnet_add'
      post 'subnet_delete'
      post 'subnet_modify'

      post 'instance_add'
      post 'instance_bash_history'
      post 'instance_chef_error'
      post 'instance_delete'
      post 'instance_modify'
      post 'instance_role_add'
      post 'instance_role_remove'
      post 'instance_dynamic_ip_roll'

      post 'group_add'
      post 'group_modify'
      post 'group_delete'

      post 'group_instructions_get'
      post 'group_instructions_modify'

      post 'group_player_add'
      post 'group_player_delete'
      post 'group_student_group_add'
      post 'group_student_group_remove'

      post 'group_admin_access_add'
      post 'group_admin_access_remove'
      post 'group_user_access_add'
      post 'group_user_access_remove'

      post 'role_add'
      post 'role_delete'
      post 'role_modify'
      post 'role_package_add'
      post 'role_package_remove'
      post 'role_recipe_add'
      post 'role_recipe_remove'

      post 'recipe_view'
      post 'recipe_update_view'
      post 'recipe_global_get'
      post 'recipe_global_add'
      post 'recipe_custom_add'
      post 'recipe_remove'
      post 'recipe_update'

      post 'scoring_question_add'
      post 'scoring_question_delete'
      post 'scoring_question_modify'
      post 'scoring_question_move_up'
      post 'scoring_question_move_down'

      post 'scoring_answers_show'
      post 'scoring_answer_essay_show'
      post 'scoring_answer_essay_grade'
      post 'scoring_answer_essay_grade_edit'
      post 'scoring_answer_essay_grade_delete'
      post 'scoring_answer_comment'
      post 'scoring_answer_comment_show'
      post 'scoring_answer_comment_edit'
      post 'scoring_answer_comment_edit_show'

    end
  end

  post 'scenarios/create_custom'
  post 'scenarios/obliterate_custom'
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get  'admin', to: 'admin#index'
  post 'admin/user_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'
  post 'admin/student_add_to_all'
  post 'admin/instructor_to_student'
  post 'admin/reset_password'
  post 'admin/student_group_create'
  post 'admin/student_group_destroy'
  post 'admin/student_group_user_add'
  post 'admin/student_group_user_remove'

  get 'instructor', to: 'instructor#index'
  post 'instructor/student_group_create'
  post 'instructor/student_group_destroy'
  post 'instructor/student_group_user_add'
  post 'instructor/student_group_user_remove'

  get 'student', to: 'student#index'
  get 'student/:id', to: 'student#show'
  post 'student/:id/answer_string', to: 'student#answer_string', as: 'answer_string_student'
  post 'student/:id/answer_number', to: 'student#answer_number', as: 'answer_number_student'
  post 'student/:id/answer_essay', to: 'student#answer_essay', as: 'answer_essay_student'
  post 'student/:id/answer_essay_delete', to: 'student#answer_essay_delete', as: 'answer_essay_delete_student'
  post 'student/:id/answer_essay_show', to: 'student#answer_essay_show', as: 'answer_essay_show_student'
  post 'student/:id/answer_comment_show', to: 'student#answer_comment_show', as: 'answer_comment_show_student'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/controllers/scenarios_controller.rb
require 'dynamic_ip'

class ScenariosController < ApplicationController
  before_action :authenticate_admin_or_instructor
  before_action :set_user

  # Scenario
  before_action :set_scenario, only: [
    :clone, :destroyme, :edit, :modify, :show, :update, :save, :save_as,
    :boot, :status, :unboot, :pause, :start,
    :cloud_add, 
    :player_modify, :player_student_group_add, :player_add, :player_group_add, :player_delete, :player_group_admin_access_add, :player_group_user_access_add,
    :role_recipe_add, :role_add,
    :recipe_custom_add, :recipe_global_add, :recipe_global_get, :recipe_remove, :recipe_update, :recipe_update_view, :recipe_view,
    :group_add, :group_instructions_get, :group_instructions_modify,
    :scoring_question_add, :scoring_answers_show, :scoring_answer_essay_show, :scoring_answer_comment, :scoring_answer_comment_show,
    :scoring_answer_comment_edit, :scoring_answer_comment_edit_show, :scoring_answer_essay_grade, :scoring_answer_essay_grade_edit,
    :scoring_answer_essay_grade_delete,
    :instructions_get, :instructions_modify, :instructions_student_get, :instructions_student_modify
  ]

  # Cloud
  before_action :set_cloud, only: [
    :boot_cloud, :unboot_cloud, :cloud_delete, :cloud_modify, :subnet_add
  ]

  # Subnet
  before_action :set_subnet, only: [
    :boot_subnet, :unboot_subnet, :subnet_delete, :subnet_modify, :instance_add
  ]

  # Instance
  before_action :set_instance, only: [
    :boot_instance, :unboot_instance, :instance_role_add, :instance_delete, :instance_bash_history, :instance_chef_error, :instance_modify,
    :instance_dynamic_ip_roll
  ]

  # Group
  before_action :set_group, only: [
    :group_delete, :group_modify, :group_admin_access_add, :group_user_access_add, :group_player_add, 
    :group_student_group_add, :group_student_group_remove, :group_instructions_get, :group_instructions_modify
  ]
  before_action :set_instance_group, only: [
    :group_admin_access_remove, :group_user_access_remove
  ]
  before_action :set_player, only: [
    :group_player_delete
  ]

  # Role
  before_action :set_role, only: [
    :role_recipe_add, :role_delete, :role_modify, :role_package_add, :role_package_remove
  ]
  before_action :set_recipe, only: [
    :recipe_remove, :recipe_update, :recipe_update_view, :recipe_update, :recipe_view
  ]
  before_action :set_role_recipe, only: [
    :role_recipe_remove
  ]
  before_action :set_instance_role, only: [
    :instance_role_remove
  ]
  before_action :set_question, only: [
    :scoring_question_delete, :scoring_question_modify, :scoring_question_move_up, :scoring_question_move_down
  ]
  before_action :set_student, only: [
    :scoring_answers_show
  ]
  before_action :set_answer, only: [
    :scoring_answer_essay_show, :scoring_answer_comment, :scoring_answer_comment_show, 
    :scoring_answer_comment_edit_show, :scoring_answer_comment_edit, :scoring_answer_essay_grade,
    :scoring_answer_essay_grade_edit, :scoring_answer_essay_grade_delete
  ]

  # GET /scenarios
  # GET /scenarios.json
  def index
    @scenarios = []
    if @user.is_admin?
      @scenarios = Scenario.all
    else
      @scenarios = Scenario.where(user_id: current_user.id)
    end
  end

  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
    # @clone = params[:clone]
    #@scenario.check_status
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
    @templates = []
    if Rails.env == 'production'
      @templates << {title: 'Production', headers: YmlRecord.yml_headers('production', @user)}
      @templates << {title: 'Local', headers: YmlRecord.yml_headers('local', @user)}
    elsif Rails.env == 'development'
      @templates << {title: 'Development', headers: YmlRecord.yml_headers('development', @user)}
      @templates << {title: 'Production', headers: YmlRecord.yml_headers('production', @user)}
      @templates << {title: 'Local', headers: YmlRecord.yml_headers('local', @user)}
      @templates << {title: 'Test', headers: YmlRecord.yml_headers('test', @user)}
    elsif Rails.env == 'test'
      @templates << {title: 'Test', headers: YmlRecord.yml_headers('test', @user)}
    end
    @templates << {title: 'Custom', headers: YmlRecord.yml_headers('custom', @user)}
  end

  # GET /scenarios/1/edit
  def edit
    @templates = []
  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    @scenario = @user.scenarios.new(scenario_params)
    @scenario.save

    respond_to do |format|
      if @scenario.errors.any?
        @scenario.destroy
        if Rails.env == 'production'
          format.html { redirect_to '/scenarios/new', alert: "There was an error creating Scenario #{@scenario.name} please contact administrator."}
        else
          format.html { redirect_to '/scenarios/new', alert: "There was an error creating Scenario #{@scenario.name}. #{@scenario.errors.messages}"}
        end
      else
        format.html { redirect_to @scenario, notice: 'Scenario was successfully created.' }
      end
    end
  end

  # PATCH/PUT /scenarios/1
  # PATCH/PUT /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.' }
        format.json { render :show, status: :ok, location: @scenario }
      else
        format.html { render :edit }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_custom
    # @scenario = Scenario.new(name: params[:name], location: :development, user_id: @user.id)
    # @scenario.save
    # # if @scenario.make_custom
    # #   @scenario.save
    # # end

    respond_to do |format|
      format.js { render "scenarios/js/scenario/create_custom.js.erb", layout: false }
    end
  end

  def obliterate_custom
    @name, path_graveyard_scenario = ScenarioManagement.new.obliterate_custom(params[:filename], @user)

    respond_to do |format|
      format.js { render "scenarios/js/scenario/obliterate_custom.js.erb", layout: false }
    end
  end

  def destroyme
    if not @scenario.modifiable?
      if @scenario.destroy
        respond_to do |format|
          format.js { render js: "window.location.pathname='/scenarios'" }
        end
      else
        respond_to do |format|
          format.js { render 'scenarios/js/scenario/destroy.js.erb', :layout => false }
        end
      end
    elsif params[:save] == nil and @scenario.modified?
      respond_to do |format|
        format.js { render 'scenarios/js/scenario/destroy.js.erb', :layout => false }
      end
    else
      if params[:save] == "true"
        @scenario.update_yml
      end
      if @scenario.destroy
        respond_to do |format|
          format.js { render js: "window.location.pathname='/scenarios'" }
        end
      else 
        respond_to do |format|
          format.js { render 'scenarios/js/scenario/destroy.js.erb', :layout => false }
        end
      end
    end

  end

  def save
    @scenario.update_yml
    respond_to do |format|
      format.js { render 'scenarios/js/scenario/save.js.erb', :layout => false }
    end
  end

  def save_as
    @scenario.change_name(params[:name])
    respond_to do |format|
      format.js { render 'scenarios/js/scenario/save_as.js.erb', :layout => false }
    end
  end

  def clone
    @clone = @scenario.clone(params[:name])
    respond_to do |format|
      format.js { render "scenarios/js/scenario/clone.js.erb", layout: false }
    end
  end

  def clone_new
    @clone = ScenarioManagement.new.clone_from_name(params[:name], params[:location], params[:newname], @user)
    respond_to do |format|
      format.js { render "scenarios/js/scenario/clone_new.js.erb", layout: false }
    end
  end

  def clone_set
    clone = Scenario.find(params[:clone_id])
    redirect_to clone, notice: 'Scenario was successfully cloned.'
  end

  def status
    @student_answers_update = []
    if params[:student_answers]
      params[:student_answers].each do |key, value|
        if student = @scenario.find_student(value['student_id'].to_i)
          oldlist = value['answers'].split(',').map{ |n| n.to_i}
          newlist = @scenario.answers_list(student)
          if (oldlist.size != newlist.size) or not (oldlist - newlist).blank?
            @student_answers_update << { student: student, show: value['show'] }
          end
        end
      end
    end  

    respond_to do |format|
      format.js { render 'scenarios/js/status.js.erb', :layout => false }
    end
  end

  #############################################################
  # BOOTING

  def boot
    @scenario.boot(dependents: true)
    respond_to do |format|
      format.js { render 'scenarios/js/boot/boot_scenario.js.erb', :layout => false }
    end
  end

  def unboot
    @scenario.unboot(dependents: true)
    respond_to do |format|
      format.js { render 'scenarios/js/boot/unboot_scenario.js.erb', :layout => false }
    end
  end

  def boot_cloud
    @cloud.boot(solo: true)
    respond_to  do |format|
      format.js { render template: 'scenarios/js/boot/boot_cloud.js.erb', layout: false }
    end
  end

  def unboot_cloud
    @cloud.unboot(solo: true)
    respond_to do |format|
      format.js { render template: 'scenarios/js/boot/unboot_cloud.js.erb',  layout: false }
    end
  end

  def boot_subnet
    @subnet.boot(solo: true)
    respond_to do |format|
      format.js { render template: 'scenarios/js/boot/boot_subnet.js.erb', layout: false }
    end
  end

  def unboot_subnet
    @subnet.unboot(solo: true)
    respond_to do |format|
      format.js { render template: 'scenarios/js/boot/unboot_subnet.js.erb', layout: false }
    end
  end

  def boot_instance
    @instance.boot(solo: true)
    respond_to do |format|
      format.js { render template: 'scenarios/js/boot/boot_instance.js.erb', layout: false }
    end
  end

  def unboot_instance
    @instance.unboot(solo: true)
    respond_to do |format|

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/edit.html.haml
%h1 Editing scenario

= render 'form'

= link_to 'Show', @scenario
\|
= link_to 'Back', scenarios_path

app/views/scenarios/index.html.haml
%div.modal#modal-scenario-destroy{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          Changes have been made to the Scenario
      %div.modal-body.inline#modalbody
        
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Cancel

%div.modal#modal-scenario-custom-new{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          Create Custom Scenario
      %div.modal-body#modalbody
        = form_tag scenarios_create_custom_path, remote:true, method: :post do
          %div#name-div
            = label_tag "Name:", nil, class: 'control-label'
            = text_field_tag "name", nil, class: 'form-control'
            %span.help-block#name-help
          %p
          %div#help-div
            %span.help-block#help-help

          = submit_tag "Submit", :class => 'btn btn-default'
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h4
        Scenarios:
    %li
      &nbsp;&nbsp;
    %li
      = link_to 'Load New Scenario', new_scenario_path, class: 'btn btn-default'
    %li
      &nbsp;&nbsp;
    %li
      = link_to 'Create Custom Scenario', "#modal-scenario-custom-new", :data => {:toggle=>"modal"}, onclick: "$('#modal-scenario-custom-new').find('#name').val(''); $('#modal-scenario-custom-new').find('#name-div').removeClass('has-error'); $('#modal-scenario-custom-new').find('#name-help').html('');", class: 'btn btn-default'

  %div.panel-body
    %dl
    %h4
      %b
        Current Scenarios:
    %br
    %table.table
      %tr
        %th Name
        %th Status
        - if @user.is_admin?
          %th Instructor
        %th

      - @scenarios.each do |scenario|
        %tr
          %td= scenario.name
          %td= scenario.status
          - if @user.is_admin?
            - if scenario.user_id
              %td= User.find(scenario.user_id).name
            - else
              %td
          %td
            %div.btn-group
              = link_to 'Show', scenario, class: 'btn btn-default'
              = link_to 'Destroy', destroyme_scenario_path(scenario), method: :post, remote: true, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/scenarios/new.html.haml
%div.modal#modal-scenario-clone{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          Clone Scenario
      %div.modal-body#modalbody
        = form_tag clone_new_scenario_path(0), remote: true, method: :post do 
          %p
          = hidden_field_tag "location"
          = hidden_field_tag "name"
          %div#name-div
            = label_tag nil, "Name:"
            = text_field_tag "newname", nil, class: 'form-control'
            %span.help-block.inline#name-help
          %br
          = submit_tag "Submit", :class => 'btn btn-default'
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h4#scenario-new-title
        New Scenario:

  %div.panel-body
    - @templates.each do |template_kind|
      %h3= "#{template_kind[:title]} Scenarios"
      %ul
        - if template_kind[:headers].empty?
          none
        - else
          - template_kind[:headers].each do |template|
            %div{ id: "scenario-#{template[:location]}-#{template[:name].downcase}"}
              %b Name:
              = template[:name]
              %br
              %b Description:
              = template[:description]
              %p
              %div.nav.nav-pills
                %li
                  = simple_form_for(@scenario) do |f|
                    = f.hidden_field :name, :value => template[:filename]
                    = f.hidden_field :location, :value => template[:location]
                    = f.button :submit, 'Create ' + template[:name], class: 'btn btn-primary'
                %li
                  = link_to 'Clone', "#modal-scenario-clone", :data => {:toggle=>"modal"}, onclick: "$('#modal-scenario-clone').find('#name-div').removeClass('has-error'); $('#modal-scenario-clone').find('#newname').val(''); $('#modal-scenario-clone').find('#name-help').html(''); $('#modal-scenario-clone').find('#name').val('#{template[:name]}'); $('#modal-scenario-clone').find('#location').val('#{template[:location]}')", class: 'btn btn-default'

                - if template_kind[:title] == 'Custom'
                  %li
                    &nbsp;&nbsp;
                  %li
                    = link_to 'Obliterate', scenarios_obliterate_custom_path(filename: template[:filename]), remote: true, method: :post, :data => { confirm: "This will completely erase the scenario. Are you sure?" }, class: 'btn btn-danger'
              %p
              %br

= link_to 'Back', scenarios_path, class: 'btn btn-default'

app/views/scenarios/show.html.haml
= render '/scenarios/show/modals'

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h4
        %b
          %span#scenario-name= @scenario.name
          \:
    %li
      &nbsp;
    %li{ id: 'boot-button-li', class: @scenario.bootable? ? "" : "disabled" }
      = link_to 'Boot', boot_scenario_path(@scenario), method: :post, remote:true, id: 'boot-button', class: 'btn btn-default'
    %li{ id: 'unboot-button-li', class: @scenario.unbootable? ? "" : "disabled" }
      = link_to 'Unboot', unboot_scenario_path(@scenario), method: :post, remote:true, id: 'unboot-button', class: 'btn btn-default'
    %li{ id: 'pause-button-li', class: @scenario.booted? ? "" : "disabled" }
      = link_to 'Pause', pause_scenario_path(@scenario), method: :post, remote:true, id: 'pause-button', class: 'btn btn-default'
    %li{ id: 'start-button-li', class: @scenario.paused? ? "" : "disabled" }
      = link_to 'Start', start_scenario_path(@scenario), method: :post, remote:true, id: 'start-button', class: 'btn btn-default'
    %li
      = link_to 'Clone', "#modal-scenario-clone", :data => {:toggle=>"modal"}, :onclick => "$('#modal-scenario-clone').find('#name-div').removeClass('has-error'); $('#modal-scenario-clone').find('#name').val(''); $('#modal-scenario-clone').find('#name-help').html('');", class: 'btn btn-default'
    %li{ id: 'destroy-button-li', class: @scenario.stopped? ? "" : "disabled" }
      = link_to 'Destroy', destroyme_scenario_path(@scenario), method: :post, remote: true, id: 'destroy-button', class: 'btn btn-default'
    - if @scenario.modifiable?
      %li{ id: "save-button-li", class: @scenario.modified? ? "" : "disabled" }
        = link_to 'Save', save_scenario_path(@scenario), method: :post, remote: true, id: 'save-button', class: 'btn btn-default', href: @scenario.modified? ? "/scenarios/#{@scenario.id}/save" : "javascript: void(0)"
      %li{ id: 'save-as-button-li', class: @scenario.stopped? ? "" : "disabled" }
        = link_to 'Save As', "#modal-scenario-save-as", :data => {:toggle=>"modal"}, id: 'save-as-button', onclick: "$('#modal-scenario-save-as').find('#name').val(''); $('#modal-scenario-save-as').find('#name-div').removeClass('has-error'); $('#modal-scenario-save-as').find('#name-help').html(''); $('#modal-scenario-save-as').find('#help-div').removeClass('has-error'); $('#modal-scenario-save-as').find('#help-help').html('');", class: 'btn btn-default'
    %li
      = link_to 'Show Log', log_get_scenario_path(@scenario, kind: 'scenario'), method: :post, remote: true, class: 'btn btn-default'

  %div.indent.panel-body
    %ul.nav.nav-tabs
      %li.active
        %a{ href: '#scenario', data: { toggle: 'tab' } } Scenario
      %li
        %a{ href: '#instances', data: { toggle: 'tab' } } Instances
      %li
        %a{ href: '#users', data: { toggle: 'tab' } } Users
      %li
        %a{ href: '#roles', data: { toggle: 'tab' } } Roles
      %li
        %a{ href: '#recipes', data: { toggle: 'tab' } } Recipes
      %li
        %a{ href: '#scoring', data: { toggle: 'tab' } } Scoring

    %div.tab-content
      %br
      %div.tab-pane.active#scenario
        = render 'scenarios/tabs/scenario'

      %div.tab-pane#instances
        = render 'scenarios/tabs/instances'

      %div.tab-pane#users
        = render 'scenarios/tabs/users'

      %div.tab-pane#roles
        = render 'scenarios/tabs/roles'

      %div.tab-pane#recipes
        = render 'scenarios/tabs/recipes'

      %div.tab-pane#scoring
        = render 'scenarios/tabs/scoring'

= link_to 'Back', scenarios_path, class: 'btn btn-default'

%script
  - if @clone
    update_flash("Scenario successfully cloned");
%script
  = "get_scnario_status('#{@scenario.id}');"
  

app/views/scenarios/status.html.haml
%h1= @scenario.name
Booted: 
= @total_booted
Total:
= @total_instances