config/routes.rb
Edurange::Application.routes.draw do

  #Static tutorial routes
  get 'tutorials/index'
  get 'tutorials/making_scenarios'
  get 'tutorials/student_manual'
  get 'tutorials/instructor_manual'
  get 'tutorials/quick_start_guide'

  get 'tutorials/ssh_inception'
  get 'tutorials/total_recon'

  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds
  resources :tutorials
  resources :statistics do
    member do  # define routing for the statistics controller methods
      # destorying statistics
      post 'destroyme'
      # downloading statistics
      get 'download_bash_history'
      get 'download_exit_status'
      get 'download_script_log'
      get 'download_all'  
      # analytics, complicated query params
      get 'generate_analytics' 
    end
  end
  

  get 'statistic/id', to: 'scenarios#id'
  

  resources :scenarios do
    member do
      post 'destroyme'

      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'
      post 'status'
      post 'pause'
      post 'start'

      post 'log_get'
      post 'clone'
      post 'clone_new'
      get  'clone_set'
      post 'save'
      post 'save_as'
      post 'obliterate_custom'

      post 'instructions_get'
      post 'instructions_modify'
      post 'instructions_student_get'
      post 'instructions_student_modify'

      post 'cloud_add'
      post 'cloud_delete'
      post 'cloud_modify'

      post 'subnet_add'
      post 'subnet_delete'
      post 'subnet_modify'

      post 'instance_add'
      post 'instance_bash_history'
      post 'instance_chef_error'
      post 'instance_delete'
      post 'instance_modify'
      post 'instance_role_add'
      post 'instance_role_remove'
      post 'instance_dynamic_ip_roll'

      post 'group_add'
      post 'group_modify'
      post 'group_delete'

      post 'group_instructions_get'
      post 'group_instructions_modify'

      post 'group_player_add'
      post 'group_player_delete'
      post 'group_student_group_add'
      post 'group_student_group_remove'

      post 'group_admin_access_add'
      post 'group_admin_access_remove'
      post 'group_user_access_add'
      post 'group_user_access_remove'

      post 'role_add'
      post 'role_delete'
      post 'role_modify'
      post 'role_package_add'
      post 'role_package_remove'
      post 'role_recipe_add'
      post 'role_recipe_remove'

      post 'recipe_view'
      post 'recipe_update_view'
      post 'recipe_global_get'
      post 'recipe_global_add'
      post 'recipe_custom_add'
      post 'recipe_remove'
      post 'recipe_update'

      post 'scoring_question_add'
      post 'scoring_question_delete'
      post 'scoring_question_modify'
      post 'scoring_question_move_up'
      post 'scoring_question_move_down'

      post 'scoring_answers_show'
      post 'scoring_answer_essay_show'
      post 'scoring_answer_essay_grade'
      post 'scoring_answer_essay_grade_edit'
      post 'scoring_answer_essay_grade_delete'
      post 'scoring_answer_comment'
      post 'scoring_answer_comment_show'
      post 'scoring_answer_comment_edit'
      post 'scoring_answer_comment_edit_show'

    end
  end

  post 'scenarios/create_custom'
  post 'scenarios/obliterate_custom'
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get  'admin', to: 'admin#index'
  post 'admin/user_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'
  post 'admin/student_add_to_all'
  post 'admin/instructor_to_student'
  post 'admin/reset_password'
  post 'admin/student_group_create'
  post 'admin/student_group_destroy'
  post 'admin/student_group_user_add'
  post 'admin/student_group_user_remove'

  get 'instructor', to: 'instructor#index'
  post 'instructor/student_group_create'
  post 'instructor/student_group_destroy'
  post 'instructor/student_group_user_add'
  post 'instructor/student_group_user_remove'

  get 'student', to: 'student#index'
  get 'student/:id', to: 'student#show'
  post 'student/:id/answer_string', to: 'student#answer_string', as: 'answer_string_student'
  post 'student/:id/answer_number', to: 'student#answer_number', as: 'answer_number_student'
  post 'student/:id/answer_essay', to: 'student#answer_essay', as: 'answer_essay_student'
  post 'student/:id/answer_essay_delete', to: 'student#answer_essay_delete', as: 'answer_essay_delete_student'
  post 'student/:id/answer_essay_show', to: 'student#answer_essay_show', as: 'answer_essay_show_student'
  post 'student/:id/answer_comment_show', to: 'student#answer_comment_show', as: 'answer_comment_show_student'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/controllers/instructor_controller.rb
class InstructorController < ApplicationController
  before_action :authenticate_instructor
  before_action :set_student_group, only: [:student_group_destroy]

  def index
    @players = Player.where(user_id: current_user.id)
  end

  def student_group_create
    @user = User.find(current_user.id)
    @student_group = @user.student_groups.new(name: params[:name])
    @student_group.save

    respond_to do |format|
      format.js { render 'instructor/js/student_group_create.js.erb', :layout => false }
    end
  end

  def student_group_destroy
    @student_group.destroy
    respond_to do |format|
      format.js { render 'instructor/js/student_group_delete.js.erb', :layout => false }
    end
  end

  def student_group_user_add
    users = User.find(params[:user_id])

    if @student_group = @user.student_groups.find_by_name(params[:student_group_name])
      @student_group_users = @student_group.user_add(users)
    end

    respond_to do |format|
      format.js { render 'instructor/js/student_group_user_add.js.erb', :layout => false }
    end
  end

  def student_group_user_remove
    @student_group_users = StudentGroupUser.find(params[:student_group_user_id])

    # student_group_user_id may or may not contain multiple ids
    if not @student_group_users.respond_to? "each"
      @student_group_users = [@student_group_users]
    end

    @student_group_users.each do |sgu|
      if sgu.student_group.user == User.find(current_user.id)
        sgu.destroy
      end
    end

    respond_to do |format|
      format.js { render 'instructor/js/student_group_user_remove.js.erb', :layout => false }
    end
  end

  private

  def set_student_group
    @student_group = StudentGroup.find(params[:student_group_id])
    if not User.find(current_user.id).owns? @student_group
      head :ok, content_type: "text/html"
      return
    end
  end

end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/views/instructor/_student.html.haml
%tr{ id: "student-group-user-#{student.id}", class: "user-#{student.user.id }" }
  - if student_group.name == "All"
    %td= check_box_tag "user_id[]", student.user.id
  - else
    %td= check_box_tag "student_group_user_id[]", student.id
  %td= student.user.name
  %td= student.user.email
  %td= student.user.organization
  - if student_group.name == "All"
    %td
      = link_to 'add to student group', '#modal-student-group-user-add', data: {toggle: "modal"},      |
          onclick: "$('#modal-student-group-user-add').find('#user-name').html('#{student.user.name}');" + |
                   "$('#modal-student-group-user-add').find('#user_id').val('#{student.user.id}');" +      |
                   "$('#modal-student-group-user-add').find('#name-div').removeClass('has-error');" +  |
                   "$('#modal-student-group-user-add').find('#student_group_name').val('');" +         |
                   "$('#modal-student-group-user-add').find('#name-help').html('');"                   |
  - else
    %td
      = link_to 'remove', instructor_student_group_user_remove_path(student_group_user_id: student.id), remote: :true,
          method: :post, data: { confirm: "Are you sure you want to delete Student Group User #{student.user.name}?" }

app/views/instructor/_student_group.html.haml
-#%div{ id: "student-group-#{student_group.id}" }

  -#%row
    -#- if student_group.name != "All"
      -#%div.pull-right
        -#= link_to '- delete group', instructor_student_group_destroy_path(student_group_id: student_group.id),
            -#remote: true, method: :post, role: "button",
            -#data: { confirm: "Are you sure you want to delete Student Group #{student_group.name}?" }
    -#%h4
      -#= student_group.name
      -#%small
        -#= link_to 'expand/collapse', "#student-group#{student_group.id}",
          -#data: { toggle: 'collapse', target: "#student-group-#{student_group.id}-collapse", parent: '#student_groups' }

  -#%div.collapse{ id: "student-group-#{student_group.id}-collapse", class: (student_group.name == "All" ? "in" : "") }
  
    -#= form_tag (student_group.name == "All" ? instructor_student_group_user_add_path(scenario) : instructor_student_group_user_remove_path(scenario)),
        -#remote: true, method: :post, class: 'form-inline' do
    
      -#%table.table{ id: "student-group-#{student_group.id}-table"}
        -#%tr
          -#%td
            -#<a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked', true);">all</a>,
            -#<a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked', false);">none</a>
          -#%th Name
          -#%th Email
          -#%th Organization
          -#%th
        -#- student_group.student_group_users.each do |student|
          -#= render 'student', student: student, scenario: @scenario, student_group: student_group
        -#%tr#foot
          -#%td{ colspan: '5' }
            -#<a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked', true);">all</a>,
            -#<a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked', false);">none</a>,
            -#- if student_group.name == "All"
              -#= link_to 'add selected to ', "javascript:void(0)", onclick: "$('#student-group-#{student_group.id} form').submit();"
              -#= select_tag 'student_group_name', options_for_select(StudentGroup.all.select{ |s| s.name != "All" }.collect{ |s| s.name }),
                  -#include_blank: "student group", class: 'form-control input-sm', id: 'student-group-select'
            -#- else
              -#= link_to 'remove selected from group', "javascript:void(0)", onclick: "$('#student-group-#{student_group.id} form').submit();"

%div{ id: "student-group-#{student_group.id}" }

  - if student_group.name != "All"
    %span.pull-right
      = link_to '- delete group', instructor_student_group_destroy_path(student_group_id: student_group.id),
          remote: true, method: :post, role: "button",
          data: { confirm: "Are you sure you want to delete Student Group #{student_group.name}?" }
  %label
    = student_group.name + ":"
    = link_to 'expand/collapse', "#student-group-#{student_group.id}",
      data: { toggle: 'collapse', target: "#student-group-#{student_group.id}-collapse", parent: '#student_groups' }

  %div.collapse{ id: "student-group-#{student_group.id}-collapse", class: (student_group.name == "All" ? "in" : "") }

    = form_tag '#', remote: true, method: :post, class: 'form-inline' do

      %table.table{ id: "student-group-#{student_group.id}-table"}
        %tr
          %td
            <a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked',true);">all</a>,
            <a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked',false);">none</a>
          %th Name
          %th Email
          %th Organization
          %th
        - student_group.student_group_users.each do |student|
          = render 'student', student: student, student_group: student_group
        %tr#foot
          %td{ colspan: '5' }
            <a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked',true);">all</a>,
            <a href="javascript:$('#student-group-#{student_group.id} input:checkbox').prop('checked',false);">none</a>,
            %b with selected:
            - if student_group.name == "All"
              = link_to 'add to ', "javascript:void(0)",
                onclick: "$('#student-group-#{student_group.id} form').attr('action','#{instructor_student_group_user_add_path}');$('#student-group-#{student_group.id} form').submit();"
              = (select_tag 'student_group_name',
                options_for_select(StudentGroup.all.select{ |s| s.name != "All" and s.user.id == current_user.id }.collect{ |s| s.name }),
                class: 'form-control input-sm', id: 'student-group-select') + ','
            - else
              = link_to 'remove', "javascript:void(0)",
                onclick: "$('#student-group-#{student_group.id} form').attr('action','#{instructor_student_group_user_remove_path}');$('#student-group-#{student_group.id} form').submit();"

app/views/instructor/index.html.haml
= render 'instructor/modals/student_group_create'
= render 'instructor/modals/student_group_user_add'

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h3
        Instructor Home

  %div.panel-body
    = render 'partials/account_information.html.haml'
    %hr

    %label Registration Code:
    %dl
      = @user.registration_code

    %hr

    %div.row
      %div.col-sm-6
        %label Student Groups:
      %div.col-sm-6.text-right
        = link_to '+ create student group', '#modal-student-group-create', data: {toggle: "modal"},   |
            onclick: "$('#modal-student-group-create').find('#name-div').removeClass('has-error');" + |
                     "$('#modal-student-group-create').find('#name').val('');" +                      |
                     "$('#modal-student-group-create').find('#name-help').html('');"                  |

    %div.list-group#student-groups
      - @user.student_groups.each do |student_group|
        = render 'student_group', student_group: student_group, scenario: @scenario

    %hr

    %label Running Scenarios:
    - if @players.size == 0
      %dl
        none

    - @players.each do |player|
      %dl
        - if scenario = Scenario.find(player.group.scenario_id)
          %label= scenario.name
          %dl
            %b.inline login:
            = player.login
            %br
            %b.inline password:
            = player.password
            %br
            %b.iniline instructions:
            = scenario.instructions
            %br